#!/bin/sh

PROG_NAME="${0##*/}"
PROG_DIR="${0%/*}"

. $PROG_DIR/pdx86-config

MAINTAINERS_FILE="$PROG_DIR/MAINTAINERS"
MAINTAINERS_DEFAULT="Darren Hart <dvhart@infradead.org>, Andy Shevchenko <andy@infradead.org>"

ML="LKML <linux-kernel@vger.kernel.org>"
MM="Linus Torvalds <torvalds@linux-foundation.org>"

TAG=$1
MSG=$TAG.$PROG_NAME

usage() {
	echo "usage: $PROG_NAME <TAG|IB>"
}

if [ $# -ne 1 ] || [ -z "$TAG" ]; then
	echo "ERROR: invalid arguments"
	usage
	exit 1
fi

git cat-file -e $TAG 2>/dev/null
if [ $? -ne 0 ]; then
	echo "$TAG is not a git object"
	exit 1
fi

TAG_TYPE=$(git cat-file -t $TAG)

# Check if it's not an existing tag
if [ "$TAG_TYPE" != "tag" ]; then
	IB=$(git name-rev --name-only --refs="$IB_PREFIX-*" $TAG)

	# Check if it's undefined name reference
	if [ "$IB" = "undefined" ]; then
		echo "ERROR: $TAG is not a tag (it's a $TAG_TYPE)"
		usage
		exit 1
	fi

	# Check if it's not an immutable branch
	if [ -z $(git branch --list --format="%(objectname)" "$IB") ]; then
		echo "ERROR: $TAG is not an immutable branch"
		usage
		exit 1
	fi
fi

if [ -e $MSG ]; then
	echo "ERROR: $MSG exists, remove or rename and try again."
	exit 1
fi

case "$TAG_TYPE" in
tag)
	SUBJECT=$(echo $TAG | sed -e "s/\($TAG_PREFIX\)-v\(.*\)/\1 for \2/" || echo $TAG)
	BODY="WRITEME: Anything relevant to the merge itself, but not the content."
	;;
commit)
	SUBJECT=$(echo $TAG | sed -e "s/$IB_PREFIX-\(.*\)/immutable branch for \1/" || echo $TAG)
	BODY="Please, pull immutable branch between $TAG_PREFIX and your subsystem."
	;;
esac

USERNAME=$(git config --get user.name)
USEREMAIL=$(git config --get user.email)

if [ -s ~/.signature ]; then
	SIGNATURE=$(cat ~/.signature)
else
	SIGNATURE="$USERNAME"
fi

if [ -s "$MAINTAINERS_FILE" ]; then
	MAINTAINERS=$(sed -e '$!s/$/, /' $MAINTAINERS_FILE | tr -d '\n')
else
	MAINTAINERS="$MAINTAINERS_DEFAULT"
fi

cat > $MSG << EOM
From: $USERNAME <$USEREMAIL>
Date: $(date -R)
To: $MM
Cc: $ML, $MAINTAINERS
Subject: [GIT PULL] $SUBJECT

Hi $(echo $MM | cut -f1 -d' '),

$BODY

Thanks,

$SIGNATURE

EOM

git request-pull $MASTER $GIT_URL $1 >> $MSG
if [ $? -ne 0 ]; then
	rm $MSG
	echo "ERROR: request pull failed"
	exit 1
fi
vim $MSG +3
if [ $? -ne 0 ]; then
	rm $MSG
	echo "ERROR: message editor failed"
	exit 1
fi
echo "Use 'mutt -H $MSG' to send the pull request."
