#!/bin/bash

PROG_NAME="${0##*/}"
PROG_DIR="${0%/*}"

. $PROG_DIR/pdx86-config

MASTER="master"

usage() {
	echo "Usage: $PROG_NAME <VERSION> <COMMIT>"
	echo "e.g. $PROG_NAME v4.4-2 for-next"
}

exit_on_error() {
	local code="$1"; shift
	local msg="$1"; shift

	[ $code -eq 0 ] && return 0

	echo "$msg"
	exit $code
}

if [ $# -ne 2 ]; then
	echo $#
	usage
	exit 1
fi

VERSION="v${1##*v}"	# Always produce "v4.4-2"-like version
COMMIT=$2		# Whatever commit ID Git recognizes
TAG="${TAG_PREFIX}-${VERSION}"

# Verify the tag does not already exist
git rev-parse $TAG &> /dev/null && exit_on_error 1 "Tag already exists: $TAG"

# Perform a sanity check before creating the tag
$PROG_DIR/pdx86-cherry $2
if [ $? -ne 0 ]; then
	echo "Duplicate commits detected, tag anyway? [y/N] "
	read RESPONSE
	[ "$RESPONSE" = "y" -o "$RESPONSE" = "Y" ] || exit_on_error $? "Aborted by user"
fi

TMP=
which tempfile &> /dev/null
if [ $? -eq 0 ]; then
	TMP=$(tempfile -s .$PROG_NAME)
else
	which mktemp &> /dev/null
	if [ $? -eq 0 ]; then
		TMP=$(mktemp --suffix=.$PROG_NAME)
	fi
fi
[ -n "$TMP" ] || exit_on_error $? "ERROR: Failed to create a suitable temp file"

PREFIX=''
(
	echo -e "$TAG_PREFIX for $VERSION\n";
	echo "WRITEME: Highlights and summary";
	echo "";
	echo "The following is an automated git shortlog grouped by driver:";
	git log --pretty='format:%s' $MASTER..$COMMIT | \
	sed -e "s,^$SUBJ_PREFIX: \?,," | \
	sort -k1,1 -t ':' -s | \
	while read line || [[ -n "$line" ]]; do
		NEW_PREFIX=$(echo $line | cut -d ':' -f1)
		SUBJECT=$(echo $line | cut -d ':' -f2-)
		if [ "$PREFIX" != "$NEW_PREFIX" ]; then
			PREFIX="$NEW_PREFIX"
			echo -e "\n$PREFIX:"
		fi
		echo " - $SUBJECT"
	done
) > $TMP
$EDITOR $TMP
exit_on_error $? "ERROR: Editor exited with error code $?."

git tag -s -F $TMP -a $TAG_PREFIX-$VERSION $COMMIT
exit_on_error $? "git tag failed. Edited tag message saved in $TMP."

echo "Created tag: $TAG"
echo "Push with 'git push pdx86 $TAG'"
rm $TMP
